### ISSUE TITLE
Format attributes

### ISSUE THREAD

**Issue by StarpTech** [rehypejs/rehype-format#5]
Hi,
is there an easy way to ident attributes in the same way as with tags? I want to archive something like this but I didn't find a ad-hoc solution to change the way how attributes are rendered. Do I need an own [renderer](https://github.com/rehypejs/rehype/tree/master/packages/rehype-stringify) or can it be archived with existing tools? Thank you.

Input:
```html
<my-component disabled name="dede" [(click)]="test" [property]="{ a: 122 }">
</my-component>
```
Output:
```html
<my-component
  disabled
  name="dede"
  [(click)]="test"
  [property]="{ a: 122 }">
</my-component>
```

**Comment by wooorm** [comment]
That would be something for `hast-util-to-html`, somewhere around [here](https://github.com/syntax-tree/hast-util-to-html/blob/06c268d1e4d20e398adaf5a275227775739cee18/lib/element.js#L67), which is used by rehype-stringify. I don’t think it would be easy though, to infer how deep an element is nested and when to start breaking: I’m sure `<my-component disabled></my-component>` could be on one line?

Also, rehype is for HTML, and I’m pretty sure all the `[]`s and `()`s won’t work well!

**Comment by StarpTech** [comment]
Thanks for the fast response. I will take a look.

> I’m sure <my-component disabled></my-component> could be on one line?

Yeah, based on the property count or max width.

> Also, rehype is for HTML, and I’m pretty sure all the []s and ()s won’t work well!

With rehype-format it works.
