### ISSUE TITLE
How to reformat just a fragment

### ISSUE THREAD

**Issue by StarpTech** [rehypejs/rehype-format#6]
Hi, when I format just an element or multiple it always includes `html`, `head`, `body` tags. How can I disable it? thanks.

**Comment by wooorm** [comment]
Could you share the code you’re using?

**Comment by StarpTech** [comment]
Here e.g https://github.com/StarpTech/prettyhtml/blob/master/index.js

The template example is in the `fixtures` folder.

**Comment by wooorm** [comment]
Did you see this? Maybe yes what you're looking for! https://github.com/rehypejs/rehype/tree/master/packages/rehype-parse

**Comment by wooorm** [comment]
(The fragment option I mean, sorry my mobile didn't update the url)

**Comment by StarpTech** [comment]
This is what I'm looking for. It's even documented but I didn't see it. I will test it. Thanks for investigating!

**Comment by wooorm** [comment]
Should work! Let me know if not!
Also I'm totally open to doc changes!
