### ISSUE TITLE
What's with update of positional informations after editing the ast?

### ISSUE THREAD

**Issue by StarpTech** [rehypejs/rehype-format#7]
I'm relative new to the rehype ecosystem and I wonder how to deal with node position updates after content manipulation? As far I see it will just formatted and ignored in all plugin but what is when I need it in order to make decisions based on the column length, row count etc...?

e.g for pretty printer to decide if the element should be wrapped on multiple lines.

Do you have an idea or tip how to solve it ?

**Comment by StarpTech** [comment]
Ok I got it 😄 

> Neither HTML nor virtual DOMs focus on positional information

**Comment by wooorm** [comment]
positional information is added to the syntax tree to enable linting. It’s described a bit in the [unist readme](https://github.com/syntax-tree/unist#position).
It should only exist for nodes that were in the original document, so if a plugins warns about it, someone could go and fix the mentioned problem at that position.
If a node were to be “generated”, aka, not in the original document but in the output document (like a table of contents), it should not have positional info.

Does that help?

**Comment by StarpTech** [comment]
@wooorm yes that makes sense. I have a different use case. After formatting my code e.g with`rehype-format` I would like to ensure that lines aren't rendered with more than 120 characters. Do you have an idea how to solve it without to reparse the result in order to restore the positional informations with parse5? I'm looking for a solution which is easy to integrate as a plugin. That's my project https://github.com/StarpTech/prettyhtml thanks!

**Comment by wooorm** [comment]
Reformatting HTML (or other syntax trees) based on how it would output is hard. And positional info isn’t going to help. You need to calculate how long parts are before you can add newlines.

I don’t see how you think positional info will help?

**Comment by StarpTech** [comment]
Your right, positional information doesn't help I mean the offset values. I thought it would be easier to implement it when I could rely on the tag offsets in order to add my custom formatting changes and decide accordingly.

**Comment by wooorm** [comment]
Alright. And good luck with this endeavour!

Can I close this?

**Comment by StarpTech** [comment]
Yes
