### ISSUE TITLE
Formatting comments

### ISSUE THREAD

**Issue by rtm** [rehypejs/rehype-format#9]
I want to leave comments on their own lines whenever possible, or at lease respect comments which were on their own lines in the input.

Currently , all newlines around comments seem to be eaten. I also note that whitespace around comments seems to be eaten. For example, `<foo> <!-- comment --> </foo>` is rendered as `<foo><!-- comment --></foo>`. Doesn't that change the semantics?

Anyway, is there any easy/obvious way to formats comments onto their own lines (in cases where the semantics would be changed by the new lines and leading space characters), or do I just need to fork `rehype-format`, or is some filter/plug-in that could handle this?

**Comment by wooorm** [comment]
👍

How this works is to first remove all whitespace, and then to add some back.
I don’t think there’s any real special care for of comments, but for a solution I think just handling them the same as elements would work.

Can you create a PR?

**Comment by rtm** [comment]
@wooorm Thanks for replying. I took a look at the code, made some obvious changes, and found myself down a rabbit hole. I'm not convinced that this is a productive direction. I switched over to using a different HTML beautifier. I also need some convincing that the current logic preserves the exact semantics of the input, in cases such as `<span>foo</span><span>bar</span>`, where the non-existence of white space between the two spans has particular semantics which would be broken by moving them onto separate lines. I also am not convinced that the whole approach of starting off by squashing is the right way to go; among other reasons, it prevents any logic based on some level of preservation of original formatting, which is desirable in some cases, and provided by other HTML formatters.

**Comment by wooorm** [comment]
Well, that was a long time!

fwiw, most of the bugs with the previous approach had to do with https://github.com/rehypejs/rehype-minify/issues/19, which you alluded to as well with “I also am not convinced that the whole approach of starting off by squashing is the right way to go”.

Stay safe!
